# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.languages_api import LanguagesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestLanguagesApi(unittest.TestCase):
    """LanguagesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.languages_api.LanguagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_alphabets_all(self):
        """Test case for v4_alphabets_all

        Returns Alphabets  # noqa: E501
        """
        pass

    def test_v4_alphabets_one(self):
        """Test case for v4_alphabets_one

        Return details on a single Alphabet  # noqa: E501
        """
        pass

    def test_v4_languages_all(self):
        """Test case for v4_languages_all

        Returns Languages  # noqa: E501
        """
        pass

    def test_v4_languages_one(self):
        """Test case for v4_languages_one

        Returns details on a single Language  # noqa: E501
        """
        pass

    def test_v4_languages_search(self):
        """Test case for v4_languages_search

        Returns languages related to this search  # noqa: E501
        """
        pass

    def test_v4_numbers_index(self):
        """Test case for v4_numbers_index

        Return all Alphabets that have a custom number sets  # noqa: E501
        """
        pass

    def test_v4_numbers_range(self):
        """Test case for v4_numbers_range

        Return a range of vernacular numbers  # noqa: E501
        """
        pass

    def test_v4_numbers_show(self):
        """Test case for v4_numbers_show

        Return a single custom number set  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
