# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.language_translation import LanguageTranslation  # noqa: E501
from openapi_client.rest import ApiException

class TestLanguageTranslation(unittest.TestCase):
    """LanguageTranslation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LanguageTranslation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.language_translation.LanguageTranslation()  # noqa: E501
        if include_optional :
            return LanguageTranslation(
                id = 0, 
                language_source_id = 17, 
                language_translation_id = 68, 
                name = 'Abkasies', 
                priority = 0, 
                created_at = '0', 
                updated_at = '0'
            )
        else :
            return LanguageTranslation(
        )

    def testLanguageTranslation(self):
        """Test LanguageTranslation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
