# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.arclight_api import ArclightApi  # noqa: E501
from openapi_client.rest import ApiException


class TestArclightApi(unittest.TestCase):
    """ArclightApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.arclight_api.ArclightApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_video_jesus_film_languages(self):
        """Test case for v4_video_jesus_film_languages

        Returns detailed metadata for a single Bible arclight  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
