# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v4_bible_all_filesets import V4BibleAllFilesets  # noqa: E501
from openapi_client.rest import ApiException

class TestV4BibleAllFilesets(unittest.TestCase):
    """V4BibleAllFilesets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V4BibleAllFilesets
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v4_bible_all_filesets.V4BibleAllFilesets()  # noqa: E501
        if include_optional :
            return V4BibleAllFilesets(
                dbp_prod = [
                    openapi_client.models.bible_fileset.Bible Fileset(
                        id = 'ENGESV', 
                        set_type_code = None, 
                        set_size_code = None, )
                    ]
            )
        else :
            return V4BibleAllFilesets(
        )

    def testV4BibleAllFilesets(self):
        """Test V4BibleAllFilesets"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
