# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.highlight import Highlight  # noqa: E501
from openapi_client.rest import ApiException

class TestHighlight(unittest.TestCase):
    """Highlight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Highlight
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.highlight.Highlight()  # noqa: E501
        if include_optional :
            return Highlight(
                id = 0, 
                user_id = '0', 
                bible_id = None, 
                book_id = None, 
                chapter = None, 
                highlighted_color = '#4488bb', 
                verse_start = None, 
                verse_sequence = None, 
                verse_end = None, 
                reference = '0', 
                project_id = None, 
                highlight_start = 0, 
                highlighted_words = 56
            )
        else :
            return Highlight(
        )

    def testHighlight(self):
        """Test Highlight"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
