# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v4_numbers_index import V4NumbersIndex  # noqa: E501
from openapi_client.rest import ApiException

class TestV4NumbersIndex(unittest.TestCase):
    """V4NumbersIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V4NumbersIndex
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v4_numbers_index.V4NumbersIndex()  # noqa: E501
        if include_optional :
            return V4NumbersIndex(
                data = [
                    openapi_client.models.v4_numbers_index_data.v4_numbers_index_data(
                        id = 'bengali', 
                        description = 'description for bengali', 
                        notes = 'notes for bengali', )
                    ]
            )
        else :
            return V4NumbersIndex(
        )

    def testV4NumbersIndex(self):
        """Test V4NumbersIndex"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
