# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.video_tag import VideoTag  # noqa: E501
from openapi_client.rest import ApiException

class TestVideoTag(unittest.TestCase):
    """VideoTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VideoTag
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.video_tag.VideoTag()  # noqa: E501
        if include_optional :
            return VideoTag(
                id = 56, 
                video_id = 56, 
                category = 56, 
                tag_type = 56, 
                tag = '0', 
                language_id = 56, 
                organization_id = 56, 
                book_id = '0', 
                chapter_start = 56, 
                chapter_end = 56, 
                verse_start = 56, 
                verse_end = 56, 
                time_begin = 56, 
                time_end = 56, 
                created_at = '0', 
                updated_at = '0'
            )
        else :
            return VideoTag(
        )

    def testVideoTag(self):
        """Test VideoTag"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
