# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.bible import Bible  # noqa: E501
from openapi_client.rest import ApiException

class TestBible(unittest.TestCase):
    """Bible unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Bible
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.bible.Bible()  # noqa: E501
        if include_optional :
            return Bible(
                custom_font_required = True, 
                id = 'ENGESV', 
                language_id = None, 
                date = 1963, 
                scope = None, 
                derived = 'English New Revised Standard Version', 
                copyright = '© 1999 Bible Society of Ghana', 
                versification = 'protestant', 
                created_at = '2018-02-12 13:32:23', 
                updated_at = '2018-02-12 13:32:23'
            )
        else :
            return Bible(
        )

    def testBible(self):
        """Test Bible"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
