# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.playlist_items import PlaylistItems  # noqa: E501
from openapi_client.rest import ApiException

class TestPlaylistItems(unittest.TestCase):
    """PlaylistItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlaylistItems
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.playlist_items.PlaylistItems()  # noqa: E501
        if include_optional :
            return PlaylistItems(
                completed = True, 
                full_chapter = True, 
                path = '0', 
                metadata = openapi_client.models.metadata.metadata(
                    bible_id = None, 
                    bible_name = None, 
                    bible_vname = None, 
                    book_name = None, ), 
                id = 56, 
                playlist_id = 56, 
                fileset_id = '0', 
                book_id = '0', 
                chapter_start = 4, 
                chapter_end = 5, 
                verse_start = '5', 
                verse_sequence = 5, 
                verse_end = 5, 
                duration = 56, 
                verses = 56, 
                updated_at = '0', 
                created_at = '0'
            )
        else :
            return PlaylistItems(
        )

    def testPlaylistItems(self):
        """Test PlaylistItems"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
