# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v4_plan_detail import V4PlanDetail  # noqa: E501
from openapi_client.rest import ApiException

class TestV4PlanDetail(unittest.TestCase):
    """V4PlanDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V4PlanDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v4_plan_detail.V4PlanDetail()  # noqa: E501
        if include_optional :
            return V4PlanDetail(
                id = None, 
                name = None, 
                featured = None, 
                thumbnail = None, 
                suggested_start_date = None, 
                created_at = None, 
                updated_at = None, 
                start_date = None, 
                percentage_completed = None, 
                user = openapi_client.models.v4_plan_index_user.v4_plan_index_user(
                    id = 56, 
                    name = '0', ), 
                days = [
                    openapi_client.models.plan_day.Plan day(
                        completed = True, 
                        id = 56, 
                        playlist_id = None, )
                    ]
            )
        else :
            return V4PlanDetail(
        )

    def testV4PlanDetail(self):
        """Test V4PlanDetail"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
