# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.audio_timing_api import AudioTimingApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAudioTimingApi(unittest.TestCase):
    """AudioTimingApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.audio_timing_api.AudioTimingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_timestamps(self):
        """Test case for v4_timestamps

        Returns Bible Filesets which have audio timestamps  # noqa: E501
        """
        pass

    def test_v4_timestamps_verse(self):
        """Test case for v4_timestamps_verse

        Returns audio timestamps for a chapter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
