# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v4_playlist_detail import V4PlaylistDetail  # noqa: E501
from openapi_client.rest import ApiException

class TestV4PlaylistDetail(unittest.TestCase):
    """V4PlaylistDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V4PlaylistDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v4_playlist_detail.V4PlaylistDetail()  # noqa: E501
        if include_optional :
            return V4PlaylistDetail(
                id = None, 
                name = None, 
                featured = None, 
                created_at = None, 
                updated_at = None, 
                external_content = None, 
                following = None, 
                user = openapi_client.models.v4_playlist_index_user.v4_playlist_index_user(
                    id = 56, 
                    name = '0', ), 
                items = [
                    openapi_client.models.playlist_item_detail.PlaylistItemDetail(
                        id = None, 
                        bible_id = None, 
                        fileset_id = None, 
                        book_id = None, 
                        chapter_start = None, 
                        chapter_end = None, 
                        verse_start = None, 
                        verse_end = None, 
                        duration = None, 
                        completed = None, )
                    ]
            )
        else :
            return V4PlaylistDetail(
        )

    def testV4PlaylistDetail(self):
        """Test V4PlaylistDetail"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
