# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.bookmark import Bookmark  # noqa: E501
from openapi_client.rest import ApiException

class TestBookmark(unittest.TestCase):
    """Bookmark unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Bookmark
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.bookmark.Bookmark()  # noqa: E501
        if include_optional :
            return Bookmark(
                id = 0, 
                book_id = None, 
                chapter = None, 
                verse_start = None, 
                verse_sequence = None, 
                user_id = None, 
                bible_id = None, 
                updated_at = '0', 
                created_at = '0'
            )
        else :
            return Bookmark(
        )

    def testBookmark(self):
        """Test Bookmark"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
