# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class BibleFileset(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'set_type_code': 'SetTypeCode',
        'set_size_code': 'SetSizeCode'
    }

    attribute_map = {
        'id': 'id',
        'set_type_code': 'set_type_code',
        'set_size_code': 'set_size_code'
    }

    def __init__(self, id=None, set_type_code=None, set_size_code=None, local_vars_configuration=None):  # noqa: E501
        """BibleFileset - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._set_type_code = None
        self._set_size_code = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if set_type_code is not None:
            self.set_type_code = set_type_code
        if set_size_code is not None:
            self.set_size_code = set_size_code

    @property
    def id(self):
        """Gets the id of this BibleFileset.  # noqa: E501

        The fileset id  # noqa: E501

        :return: The id of this BibleFileset.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BibleFileset.

        The fileset id  # noqa: E501

        :param id: The id of this BibleFileset.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                id is not None and len(id) > 16):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `16`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                id is not None and len(id) < 6):
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `6`")  # noqa: E501

        self._id = id

    @property
    def set_type_code(self):
        """Gets the set_type_code of this BibleFileset.  # noqa: E501


        :return: The set_type_code of this BibleFileset.  # noqa: E501
        :rtype: SetTypeCode
        """
        return self._set_type_code

    @set_type_code.setter
    def set_type_code(self, set_type_code):
        """Sets the set_type_code of this BibleFileset.


        :param set_type_code: The set_type_code of this BibleFileset.  # noqa: E501
        :type: SetTypeCode
        """

        self._set_type_code = set_type_code

    @property
    def set_size_code(self):
        """Gets the set_size_code of this BibleFileset.  # noqa: E501


        :return: The set_size_code of this BibleFileset.  # noqa: E501
        :rtype: SetSizeCode
        """
        return self._set_size_code

    @set_size_code.setter
    def set_size_code(self, set_size_code):
        """Sets the set_size_code of this BibleFileset.


        :param set_size_code: The set_size_code of this BibleFileset.  # noqa: E501
        :type: SetSizeCode
        """

        self._set_size_code = set_size_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BibleFileset):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BibleFileset):
            return True

        return self.to_dict() != other.to_dict()
