# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class BibleFilesetType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'set_type_code': 'str',
        'name': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'set_type_code': 'set_type_code',
        'name': 'name',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, set_type_code=None, name=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """BibleFilesetType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._set_type_code = None
        self._name = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if set_type_code is not None:
            self.set_type_code = set_type_code
        if name is not None:
            self.name = name
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this BibleFilesetType.  # noqa: E501


        :return: The id of this BibleFilesetType.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BibleFilesetType.


        :param id: The id of this BibleFilesetType.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def set_type_code(self):
        """Gets the set_type_code of this BibleFilesetType.  # noqa: E501

        The set_type_code indicating the type of the fileset  # noqa: E501

        :return: The set_type_code of this BibleFilesetType.  # noqa: E501
        :rtype: str
        """
        return self._set_type_code

    @set_type_code.setter
    def set_type_code(self, set_type_code):
        """Sets the set_type_code of this BibleFilesetType.

        The set_type_code indicating the type of the fileset  # noqa: E501

        :param set_type_code: The set_type_code of this BibleFilesetType.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                set_type_code is not None and len(set_type_code) > 18):
            raise ValueError("Invalid value for `set_type_code`, length must be less than or equal to `18`")  # noqa: E501

        self._set_type_code = set_type_code

    @property
    def name(self):
        """Gets the name of this BibleFilesetType.  # noqa: E501

        The name of the fileset type  # noqa: E501

        :return: The name of this BibleFilesetType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BibleFilesetType.

        The name of the fileset type  # noqa: E501

        :param name: The name of this BibleFilesetType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def created_at(self):
        """Gets the created_at of this BibleFilesetType.  # noqa: E501


        :return: The created_at of this BibleFilesetType.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this BibleFilesetType.


        :param created_at: The created_at of this BibleFilesetType.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this BibleFilesetType.  # noqa: E501


        :return: The updated_at of this BibleFilesetType.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this BibleFilesetType.


        :param updated_at: The updated_at of this BibleFilesetType.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BibleFilesetType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BibleFilesetType):
            return True

        return self.to_dict() != other.to_dict()
