# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V4CountriesOneData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'Name',
        'continent_code': 'Continent',
        'languages': 'object'
    }

    attribute_map = {
        'name': 'name',
        'continent_code': 'continent_code',
        'languages': 'languages'
    }

    def __init__(self, name=None, continent_code=None, languages=None, local_vars_configuration=None):  # noqa: E501
        """V4CountriesOneData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._continent_code = None
        self._languages = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if continent_code is not None:
            self.continent_code = continent_code
        if languages is not None:
            self.languages = languages

    @property
    def name(self):
        """Gets the name of this V4CountriesOneData.  # noqa: E501


        :return: The name of this V4CountriesOneData.  # noqa: E501
        :rtype: Name
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V4CountriesOneData.


        :param name: The name of this V4CountriesOneData.  # noqa: E501
        :type: Name
        """

        self._name = name

    @property
    def continent_code(self):
        """Gets the continent_code of this V4CountriesOneData.  # noqa: E501


        :return: The continent_code of this V4CountriesOneData.  # noqa: E501
        :rtype: Continent
        """
        return self._continent_code

    @continent_code.setter
    def continent_code(self, continent_code):
        """Sets the continent_code of this V4CountriesOneData.


        :param continent_code: The continent_code of this V4CountriesOneData.  # noqa: E501
        :type: Continent
        """

        self._continent_code = continent_code

    @property
    def languages(self):
        """Gets the languages of this V4CountriesOneData.  # noqa: E501


        :return: The languages of this V4CountriesOneData.  # noqa: E501
        :rtype: object
        """
        return self._languages

    @languages.setter
    def languages(self, languages):
        """Sets the languages of this V4CountriesOneData.


        :param languages: The languages of this V4CountriesOneData.  # noqa: E501
        :type: object
        """

        self._languages = languages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V4CountriesOneData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V4CountriesOneData):
            return True

        return self.to_dict() != other.to_dict()
