# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V4Note(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'Id',
        'bible_id': 'BibleId',
        'book_id': 'BookId',
        'book_name': 'Name',
        'chapter': 'Chapter',
        'verse_start': 'VerseStart',
        'verse_start_alt': 'VerseStart',
        'verse_end': 'VerseEnd',
        'verse_end_alt': 'VerseEnd',
        'verse_text': 'VerseText',
        'notes': 'Notes',
        'created_at': 'CreatedAt',
        'updated_at': 'UpdatedAt',
        'bible_name': 'BibleName',
        'tags': 'AnnotationTag'
    }

    attribute_map = {
        'id': 'id',
        'bible_id': 'bible_id',
        'book_id': 'book_id',
        'book_name': 'book_name',
        'chapter': 'chapter',
        'verse_start': 'verse_start',
        'verse_start_alt': 'verse_start_alt',
        'verse_end': 'verse_end',
        'verse_end_alt': 'verse_end_alt',
        'verse_text': 'verse_text',
        'notes': 'notes',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'bible_name': 'bible_name',
        'tags': 'tags'
    }

    def __init__(self, id=None, bible_id=None, book_id=None, book_name=None, chapter=None, verse_start=None, verse_start_alt=None, verse_end=None, verse_end_alt=None, verse_text=None, notes=None, created_at=None, updated_at=None, bible_name=None, tags=None, local_vars_configuration=None):  # noqa: E501
        """V4Note - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._bible_id = None
        self._book_id = None
        self._book_name = None
        self._chapter = None
        self._verse_start = None
        self._verse_start_alt = None
        self._verse_end = None
        self._verse_end_alt = None
        self._verse_text = None
        self._notes = None
        self._created_at = None
        self._updated_at = None
        self._bible_name = None
        self._tags = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if bible_id is not None:
            self.bible_id = bible_id
        if book_id is not None:
            self.book_id = book_id
        if book_name is not None:
            self.book_name = book_name
        if chapter is not None:
            self.chapter = chapter
        if verse_start is not None:
            self.verse_start = verse_start
        if verse_start_alt is not None:
            self.verse_start_alt = verse_start_alt
        if verse_end is not None:
            self.verse_end = verse_end
        if verse_end_alt is not None:
            self.verse_end_alt = verse_end_alt
        if verse_text is not None:
            self.verse_text = verse_text
        if notes is not None:
            self.notes = notes
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if bible_name is not None:
            self.bible_name = bible_name
        if tags is not None:
            self.tags = tags

    @property
    def id(self):
        """Gets the id of this V4Note.  # noqa: E501


        :return: The id of this V4Note.  # noqa: E501
        :rtype: Id
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V4Note.


        :param id: The id of this V4Note.  # noqa: E501
        :type: Id
        """

        self._id = id

    @property
    def bible_id(self):
        """Gets the bible_id of this V4Note.  # noqa: E501


        :return: The bible_id of this V4Note.  # noqa: E501
        :rtype: BibleId
        """
        return self._bible_id

    @bible_id.setter
    def bible_id(self, bible_id):
        """Sets the bible_id of this V4Note.


        :param bible_id: The bible_id of this V4Note.  # noqa: E501
        :type: BibleId
        """

        self._bible_id = bible_id

    @property
    def book_id(self):
        """Gets the book_id of this V4Note.  # noqa: E501


        :return: The book_id of this V4Note.  # noqa: E501
        :rtype: BookId
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id):
        """Sets the book_id of this V4Note.


        :param book_id: The book_id of this V4Note.  # noqa: E501
        :type: BookId
        """

        self._book_id = book_id

    @property
    def book_name(self):
        """Gets the book_name of this V4Note.  # noqa: E501


        :return: The book_name of this V4Note.  # noqa: E501
        :rtype: Name
        """
        return self._book_name

    @book_name.setter
    def book_name(self, book_name):
        """Sets the book_name of this V4Note.


        :param book_name: The book_name of this V4Note.  # noqa: E501
        :type: Name
        """

        self._book_name = book_name

    @property
    def chapter(self):
        """Gets the chapter of this V4Note.  # noqa: E501


        :return: The chapter of this V4Note.  # noqa: E501
        :rtype: Chapter
        """
        return self._chapter

    @chapter.setter
    def chapter(self, chapter):
        """Sets the chapter of this V4Note.


        :param chapter: The chapter of this V4Note.  # noqa: E501
        :type: Chapter
        """

        self._chapter = chapter

    @property
    def verse_start(self):
        """Gets the verse_start of this V4Note.  # noqa: E501


        :return: The verse_start of this V4Note.  # noqa: E501
        :rtype: VerseStart
        """
        return self._verse_start

    @verse_start.setter
    def verse_start(self, verse_start):
        """Sets the verse_start of this V4Note.


        :param verse_start: The verse_start of this V4Note.  # noqa: E501
        :type: VerseStart
        """

        self._verse_start = verse_start

    @property
    def verse_start_alt(self):
        """Gets the verse_start_alt of this V4Note.  # noqa: E501


        :return: The verse_start_alt of this V4Note.  # noqa: E501
        :rtype: VerseStart
        """
        return self._verse_start_alt

    @verse_start_alt.setter
    def verse_start_alt(self, verse_start_alt):
        """Sets the verse_start_alt of this V4Note.


        :param verse_start_alt: The verse_start_alt of this V4Note.  # noqa: E501
        :type: VerseStart
        """

        self._verse_start_alt = verse_start_alt

    @property
    def verse_end(self):
        """Gets the verse_end of this V4Note.  # noqa: E501


        :return: The verse_end of this V4Note.  # noqa: E501
        :rtype: VerseEnd
        """
        return self._verse_end

    @verse_end.setter
    def verse_end(self, verse_end):
        """Sets the verse_end of this V4Note.


        :param verse_end: The verse_end of this V4Note.  # noqa: E501
        :type: VerseEnd
        """

        self._verse_end = verse_end

    @property
    def verse_end_alt(self):
        """Gets the verse_end_alt of this V4Note.  # noqa: E501


        :return: The verse_end_alt of this V4Note.  # noqa: E501
        :rtype: VerseEnd
        """
        return self._verse_end_alt

    @verse_end_alt.setter
    def verse_end_alt(self, verse_end_alt):
        """Sets the verse_end_alt of this V4Note.


        :param verse_end_alt: The verse_end_alt of this V4Note.  # noqa: E501
        :type: VerseEnd
        """

        self._verse_end_alt = verse_end_alt

    @property
    def verse_text(self):
        """Gets the verse_text of this V4Note.  # noqa: E501


        :return: The verse_text of this V4Note.  # noqa: E501
        :rtype: VerseText
        """
        return self._verse_text

    @verse_text.setter
    def verse_text(self, verse_text):
        """Sets the verse_text of this V4Note.


        :param verse_text: The verse_text of this V4Note.  # noqa: E501
        :type: VerseText
        """

        self._verse_text = verse_text

    @property
    def notes(self):
        """Gets the notes of this V4Note.  # noqa: E501


        :return: The notes of this V4Note.  # noqa: E501
        :rtype: Notes
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this V4Note.


        :param notes: The notes of this V4Note.  # noqa: E501
        :type: Notes
        """

        self._notes = notes

    @property
    def created_at(self):
        """Gets the created_at of this V4Note.  # noqa: E501


        :return: The created_at of this V4Note.  # noqa: E501
        :rtype: CreatedAt
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this V4Note.


        :param created_at: The created_at of this V4Note.  # noqa: E501
        :type: CreatedAt
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this V4Note.  # noqa: E501


        :return: The updated_at of this V4Note.  # noqa: E501
        :rtype: UpdatedAt
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this V4Note.


        :param updated_at: The updated_at of this V4Note.  # noqa: E501
        :type: UpdatedAt
        """

        self._updated_at = updated_at

    @property
    def bible_name(self):
        """Gets the bible_name of this V4Note.  # noqa: E501


        :return: The bible_name of this V4Note.  # noqa: E501
        :rtype: BibleName
        """
        return self._bible_name

    @bible_name.setter
    def bible_name(self, bible_name):
        """Sets the bible_name of this V4Note.


        :param bible_name: The bible_name of this V4Note.  # noqa: E501
        :type: BibleName
        """

        self._bible_name = bible_name

    @property
    def tags(self):
        """Gets the tags of this V4Note.  # noqa: E501


        :return: The tags of this V4Note.  # noqa: E501
        :rtype: AnnotationTag
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this V4Note.


        :param tags: The tags of this V4Note.  # noqa: E501
        :type: AnnotationTag
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V4Note):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V4Note):
            return True

        return self.to_dict() != other.to_dict()
