# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V4NumbersRangeData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'numeral': 'str',
        'numeral_vernacular': 'str'
    }

    attribute_map = {
        'numeral': 'numeral',
        'numeral_vernacular': 'numeral_vernacular'
    }

    def __init__(self, numeral=None, numeral_vernacular=None, local_vars_configuration=None):  # noqa: E501
        """V4NumbersRangeData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._numeral = None
        self._numeral_vernacular = None
        self.discriminator = None

        if numeral is not None:
            self.numeral = numeral
        if numeral_vernacular is not None:
            self.numeral_vernacular = numeral_vernacular

    @property
    def numeral(self):
        """Gets the numeral of this V4NumbersRangeData.  # noqa: E501


        :return: The numeral of this V4NumbersRangeData.  # noqa: E501
        :rtype: str
        """
        return self._numeral

    @numeral.setter
    def numeral(self, numeral):
        """Sets the numeral of this V4NumbersRangeData.


        :param numeral: The numeral of this V4NumbersRangeData.  # noqa: E501
        :type: str
        """

        self._numeral = numeral

    @property
    def numeral_vernacular(self):
        """Gets the numeral_vernacular of this V4NumbersRangeData.  # noqa: E501


        :return: The numeral_vernacular of this V4NumbersRangeData.  # noqa: E501
        :rtype: str
        """
        return self._numeral_vernacular

    @numeral_vernacular.setter
    def numeral_vernacular(self, numeral_vernacular):
        """Sets the numeral_vernacular of this V4NumbersRangeData.


        :param numeral_vernacular: The numeral_vernacular of this V4NumbersRangeData.  # noqa: E501
        :type: str
        """

        self._numeral_vernacular = numeral_vernacular

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V4NumbersRangeData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V4NumbersRangeData):
            return True

        return self.to_dict() != other.to_dict()
