# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.bible_file import BibleFile  # noqa: E501
from openapi_client.rest import ApiException

class TestBibleFile(unittest.TestCase):
    """BibleFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BibleFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.bible_file.BibleFile()  # noqa: E501
        if include_optional :
            return BibleFile(
                id = 4, 
                book_id = 'MAT', 
                chapter_start = '4', 
                verse_sequence = 10, 
                chapter_end = '5', 
                verse_start = '5', 
                verse_end = '5', 
                verse_text = 'And God said unto Abraham, And as for thee, thou shalt keep my covenant, thou, and thy seed after thee throughout their generations.', 
                file_name = 'ACHBSU_70_MAT_1.html', 
                file_size = 5486618, 
                duration = 683
            )
        else :
            return BibleFile(
        )

    def testBibleFile(self):
        """Test BibleFile"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
