# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.bibles_api import BiblesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBiblesApi(unittest.TestCase):
    """BiblesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.bibles_api.BiblesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_bible_all(self):
        """Test case for v4_bible_all

        Returns Bibles based on filter criteria  # noqa: E501
        """
        pass

    def test_v4_bible_books(self):
        """Test case for v4_bible_books

        Book information for a Bible  # noqa: E501
        """
        pass

    def test_v4_bible_by_id_search(self):
        """Test case for v4_bible_by_id_search

        Returns metadata for all bibles meeting the given version in it's Bible ID  # noqa: E501
        """
        pass

    def test_v4_bible_copyright(self):
        """Test case for v4_bible_copyright

        Bible Copyright information  # noqa: E501
        """
        pass

    def test_v4_bible_defaults(self):
        """Test case for v4_bible_defaults

        Default Bible for a language  # noqa: E501
        """
        pass

    def test_v4_bible_filesets_show_chapter(self):
        """Test case for v4_bible_filesets_show_chapter

        Returns content for a single fileset, book and chapter  # noqa: E501
        """
        pass

    def test_v4_bible_filesets_types(self):
        """Test case for v4_bible_filesets_types

        Available fileset types  # noqa: E501
        """
        pass

    def test_v4_bible_one(self):
        """Test case for v4_bible_one

        Returns detailed metadata for a single Bible  # noqa: E501
        """
        pass

    def test_v4_bible_search(self):
        """Test case for v4_bible_search

        Returns metadata for all bibles meeting the search_text in it's name  # noqa: E501
        """
        pass

    def test_v4_download(self):
        """Test case for v4_download

        Download specific fileset  # noqa: E501
        """
        pass

    def test_v4_download_list(self):
        """Test case for v4_download_list

        List of filesets which can be downloaded for this API key  # noqa: E501
        """
        pass

    def test_v4_timestamps_verse(self):
        """Test case for v4_timestamps_verse

        Returns audio timestamps for a chapter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
