# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.annotations_api import AnnotationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.annotations_api.AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_users_download(self):
        """Test case for v4_users_download

        Download annotations for specific user and bible fileset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
