# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class BibleVersesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v4_bible_verses_verse_by_bible(self, bible_id, book_id, chapter, verse_number, v, **kwargs):  # noqa: E501
        """Returns Bibles Verses based on filter criteria  # noqa: E501

        The base bible route returning by default bibles and filesets that your key has access to  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v4_bible_verses_verse_by_bible(bible_id, book_id, chapter, verse_number, v, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Id bible_id: The Bible ID to filter bible_verses by (required)
        :param Id book_id: The book to filter bible_verses by (required)
        :param Chapter chapter: The chapter to filter bible_verses by (required)
        :param VerseNumber verse_number: The verse start to filter bible_verses by (required)
        :param int v: The Version Number (required)
        :param int page: The current page of the results
        :param int limit: The number of search results to return
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: V4BibleVersesAll
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.v4_bible_verses_verse_by_bible_with_http_info(bible_id, book_id, chapter, verse_number, v, **kwargs)  # noqa: E501

    def v4_bible_verses_verse_by_bible_with_http_info(self, bible_id, book_id, chapter, verse_number, v, **kwargs):  # noqa: E501
        """Returns Bibles Verses based on filter criteria  # noqa: E501

        The base bible route returning by default bibles and filesets that your key has access to  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v4_bible_verses_verse_by_bible_with_http_info(bible_id, book_id, chapter, verse_number, v, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Id bible_id: The Bible ID to filter bible_verses by (required)
        :param Id book_id: The book to filter bible_verses by (required)
        :param Chapter chapter: The chapter to filter bible_verses by (required)
        :param VerseNumber verse_number: The verse start to filter bible_verses by (required)
        :param int v: The Version Number (required)
        :param int page: The current page of the results
        :param int limit: The number of search results to return
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(V4BibleVersesAll, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'bible_id',
            'book_id',
            'chapter',
            'verse_number',
            'v',
            'page',
            'limit'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v4_bible_verses_verse_by_bible" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'bible_id' is set
        if self.api_client.client_side_validation and ('bible_id' not in local_var_params or  # noqa: E501
                                                        local_var_params['bible_id'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `bible_id` when calling `v4_bible_verses_verse_by_bible`")  # noqa: E501
        # verify the required parameter 'book_id' is set
        if self.api_client.client_side_validation and ('book_id' not in local_var_params or  # noqa: E501
                                                        local_var_params['book_id'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `book_id` when calling `v4_bible_verses_verse_by_bible`")  # noqa: E501
        # verify the required parameter 'chapter' is set
        if self.api_client.client_side_validation and ('chapter' not in local_var_params or  # noqa: E501
                                                        local_var_params['chapter'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `chapter` when calling `v4_bible_verses_verse_by_bible`")  # noqa: E501
        # verify the required parameter 'verse_number' is set
        if self.api_client.client_side_validation and ('verse_number' not in local_var_params or  # noqa: E501
                                                        local_var_params['verse_number'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `verse_number` when calling `v4_bible_verses_verse_by_bible`")  # noqa: E501
        # verify the required parameter 'v' is set
        if self.api_client.client_side_validation and ('v' not in local_var_params or  # noqa: E501
                                                        local_var_params['v'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `v` when calling `v4_bible_verses_verse_by_bible`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bible_id' in local_var_params:
            path_params['bible_id'] = local_var_params['bible_id']  # noqa: E501
        if 'book_id' in local_var_params:
            path_params['book_id'] = local_var_params['book_id']  # noqa: E501
        if 'verse_number' in local_var_params:
            path_params['verse_number'] = local_var_params['verse_number']  # noqa: E501

        query_params = []
        if 'chapter' in local_var_params and local_var_params['chapter'] is not None:  # noqa: E501
            query_params.append(('chapter', local_var_params['chapter']))  # noqa: E501
        if 'page' in local_var_params and local_var_params['page'] is not None:  # noqa: E501
            query_params.append(('page', local_var_params['page']))  # noqa: E501
        if 'limit' in local_var_params and local_var_params['limit'] is not None:  # noqa: E501
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'v' in local_var_params and local_var_params['v'] is not None:  # noqa: E501
            query_params.append(('v', local_var_params['v']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['dbp_key']  # noqa: E501

        return self.api_client.call_api(
            '/bible/{bible_id}/verses/{book_id}/{chapter_id}/{verse_number?}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='V4BibleVersesAll',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v4_bible_verses_verse_by_language(self, language_code, book_id, chapter, verse_number, v, **kwargs):  # noqa: E501
        """Returns Bibles Verses based on filter criteria  # noqa: E501

        The base bible route returning by default bibles and filesets that your key has access to  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v4_bible_verses_verse_by_language(language_code, book_id, chapter, verse_number, v, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Id language_code: (required)
        :param Id book_id: The book to filter bible_verses by (required)
        :param Chapter chapter: The chapter to filter bible_verses by (required)
        :param VerseNumber verse_number: The verse start to filter bible_verses by (required)
        :param int v: The Version Number (required)
        :param int page: The current page of the results
        :param int limit: The number of search results to return
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: V4BibleVersesAll
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.v4_bible_verses_verse_by_language_with_http_info(language_code, book_id, chapter, verse_number, v, **kwargs)  # noqa: E501

    def v4_bible_verses_verse_by_language_with_http_info(self, language_code, book_id, chapter, verse_number, v, **kwargs):  # noqa: E501
        """Returns Bibles Verses based on filter criteria  # noqa: E501

        The base bible route returning by default bibles and filesets that your key has access to  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v4_bible_verses_verse_by_language_with_http_info(language_code, book_id, chapter, verse_number, v, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param Id language_code: (required)
        :param Id book_id: The book to filter bible_verses by (required)
        :param Chapter chapter: The chapter to filter bible_verses by (required)
        :param VerseNumber verse_number: The verse start to filter bible_verses by (required)
        :param int v: The Version Number (required)
        :param int page: The current page of the results
        :param int limit: The number of search results to return
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(V4BibleVersesAll, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'language_code',
            'book_id',
            'chapter',
            'verse_number',
            'v',
            'page',
            'limit'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v4_bible_verses_verse_by_language" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'language_code' is set
        if self.api_client.client_side_validation and ('language_code' not in local_var_params or  # noqa: E501
                                                        local_var_params['language_code'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `language_code` when calling `v4_bible_verses_verse_by_language`")  # noqa: E501
        # verify the required parameter 'book_id' is set
        if self.api_client.client_side_validation and ('book_id' not in local_var_params or  # noqa: E501
                                                        local_var_params['book_id'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `book_id` when calling `v4_bible_verses_verse_by_language`")  # noqa: E501
        # verify the required parameter 'chapter' is set
        if self.api_client.client_side_validation and ('chapter' not in local_var_params or  # noqa: E501
                                                        local_var_params['chapter'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `chapter` when calling `v4_bible_verses_verse_by_language`")  # noqa: E501
        # verify the required parameter 'verse_number' is set
        if self.api_client.client_side_validation and ('verse_number' not in local_var_params or  # noqa: E501
                                                        local_var_params['verse_number'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `verse_number` when calling `v4_bible_verses_verse_by_language`")  # noqa: E501
        # verify the required parameter 'v' is set
        if self.api_client.client_side_validation and ('v' not in local_var_params or  # noqa: E501
                                                        local_var_params['v'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `v` when calling `v4_bible_verses_verse_by_language`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'language_code' in local_var_params:
            path_params['language_code'] = local_var_params['language_code']  # noqa: E501
        if 'book_id' in local_var_params:
            path_params['book_id'] = local_var_params['book_id']  # noqa: E501
        if 'verse_number' in local_var_params:
            path_params['verse_number'] = local_var_params['verse_number']  # noqa: E501

        query_params = []
        if 'chapter' in local_var_params and local_var_params['chapter'] is not None:  # noqa: E501
            query_params.append(('chapter', local_var_params['chapter']))  # noqa: E501
        if 'page' in local_var_params and local_var_params['page'] is not None:  # noqa: E501
            query_params.append(('page', local_var_params['page']))  # noqa: E501
        if 'limit' in local_var_params and local_var_params['limit'] is not None:  # noqa: E501
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'v' in local_var_params and local_var_params['v'] is not None:  # noqa: E501
            query_params.append(('v', local_var_params['v']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['dbp_key']  # noqa: E501

        return self.api_client.call_api(
            '/bibles/verses/{language_code}/{book_id}/{chapter_id}/{verse_number?}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='V4BibleVersesAll',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
