# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class BibleFilesetSize(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'set_size_code': 'str',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'set_size_code': 'set_size_code',
        'name': 'name'
    }

    def __init__(self, id=None, set_size_code=None, name=None, local_vars_configuration=None):  # noqa: E501
        """BibleFilesetSize - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._set_size_code = None
        self._name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if set_size_code is not None:
            self.set_size_code = set_size_code
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this BibleFilesetSize.  # noqa: E501

        The id  # noqa: E501

        :return: The id of this BibleFilesetSize.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BibleFilesetSize.

        The id  # noqa: E501

        :param id: The id of this BibleFilesetSize.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                id is not None and id < 0):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._id = id

    @property
    def set_size_code(self):
        """Gets the set_size_code of this BibleFilesetSize.  # noqa: E501

        The id  # noqa: E501

        :return: The set_size_code of this BibleFilesetSize.  # noqa: E501
        :rtype: str
        """
        return self._set_size_code

    @set_size_code.setter
    def set_size_code(self, set_size_code):
        """Sets the set_size_code of this BibleFilesetSize.

        The id  # noqa: E501

        :param set_size_code: The set_size_code of this BibleFilesetSize.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                set_size_code is not None and len(set_size_code) > 9):
            raise ValueError("Invalid value for `set_size_code`, length must be less than or equal to `9`")  # noqa: E501

        self._set_size_code = set_size_code

    @property
    def name(self):
        """Gets the name of this BibleFilesetSize.  # noqa: E501

        The name  # noqa: E501

        :return: The name of this BibleFilesetSize.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BibleFilesetSize.

        The name  # noqa: E501

        :param name: The name of this BibleFilesetSize.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 191):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `191`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BibleFilesetSize):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BibleFilesetSize):
            return True

        return self.to_dict() != other.to_dict()
