# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class User(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'password': 'str',
        'nickname': 'str',
        'avatar': 'str',
        'email': 'str',
        'verified': 'bool',
        'email_token': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'password': 'password',
        'nickname': 'nickname',
        'avatar': 'avatar',
        'email': 'email',
        'verified': 'verified',
        'email_token': 'email_token'
    }

    def __init__(self, id=None, name=None, password=None, nickname=None, avatar=None, email=None, verified=None, email_token=None, local_vars_configuration=None):  # noqa: E501
        """User - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._password = None
        self._nickname = None
        self._avatar = None
        self._email = None
        self._verified = None
        self._email_token = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if password is not None:
            self.password = password
        self.nickname = nickname
        self.avatar = avatar
        if email is not None:
            self.email = email
        if verified is not None:
            self.verified = verified
        if email_token is not None:
            self.email_token = email_token

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501

        The unique id for the user  # noqa: E501

        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.

        The unique id for the user  # noqa: E501

        :param id: The id of this User.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                id is not None and id < 1):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this User.  # noqa: E501

        The name of the user  # noqa: E501

        :return: The name of this User.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.

        The name of the user  # noqa: E501

        :param name: The name of this User.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 191):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `191`")  # noqa: E501

        self._name = name

    @property
    def password(self):
        """Gets the password of this User.  # noqa: E501

        The password for the user's account  # noqa: E501

        :return: The password of this User.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this User.

        The password for the user's account  # noqa: E501

        :param password: The password of this User.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                password is not None and len(password) > 191):
            raise ValueError("Invalid value for `password`, length must be less than or equal to `191`")  # noqa: E501

        self._password = password

    @property
    def nickname(self):
        """Gets the nickname of this User.  # noqa: E501

        The preferred name for the user or an informal means of addressing them  # noqa: E501

        :return: The nickname of this User.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this User.

        The preferred name for the user or an informal means of addressing them  # noqa: E501

        :param nickname: The nickname of this User.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def avatar(self):
        """Gets the avatar of this User.  # noqa: E501

        The url to the user's profile picture  # noqa: E501

        :return: The avatar of this User.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this User.

        The url to the user's profile picture  # noqa: E501

        :param avatar: The avatar of this User.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501

        The user's email address  # noqa: E501

        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.

        The user's email address  # noqa: E501

        :param email: The email of this User.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def verified(self):
        """Gets the verified of this User.  # noqa: E501

        If the user has verified the email address they've provided or if they're connected via a social account  # noqa: E501

        :return: The verified of this User.  # noqa: E501
        :rtype: bool
        """
        return self._verified

    @verified.setter
    def verified(self, verified):
        """Sets the verified of this User.

        If the user has verified the email address they've provided or if they're connected via a social account  # noqa: E501

        :param verified: The verified of this User.  # noqa: E501
        :type: bool
        """

        self._verified = verified

    @property
    def email_token(self):
        """Gets the email_token of this User.  # noqa: E501

        The token sent to the user to verify that user's email  # noqa: E501

        :return: The email_token of this User.  # noqa: E501
        :rtype: str
        """
        return self._email_token

    @email_token.setter
    def email_token(self, email_token):
        """Sets the email_token of this User.

        The token sent to the user to verify that user's email  # noqa: E501

        :param email_token: The email_token of this User.  # noqa: E501
        :type: str
        """

        self._email_token = email_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, User):
            return True

        return self.to_dict() != other.to_dict()
