# coding: utf-8

"""
    Digital Bible Platform

    Fast, easy, and free API access to video, audio, and text Bibles.  # noqa: E501

    The version of the OpenAPI document: 4.0.0-beta
    Contact: support@digitalbibleplatform.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V4AudioTimestampsData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'book': 'BookId',
        'chapter': 'ChapterStart',
        'verse_start': 'VerseStart',
        'timestamp': 'Timestamp'
    }

    attribute_map = {
        'book': 'book',
        'chapter': 'chapter',
        'verse_start': 'verse_start',
        'timestamp': 'timestamp'
    }

    def __init__(self, book=None, chapter=None, verse_start=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """V4AudioTimestampsData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._book = None
        self._chapter = None
        self._verse_start = None
        self._timestamp = None
        self.discriminator = None

        if book is not None:
            self.book = book
        if chapter is not None:
            self.chapter = chapter
        if verse_start is not None:
            self.verse_start = verse_start
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def book(self):
        """Gets the book of this V4AudioTimestampsData.  # noqa: E501


        :return: The book of this V4AudioTimestampsData.  # noqa: E501
        :rtype: BookId
        """
        return self._book

    @book.setter
    def book(self, book):
        """Sets the book of this V4AudioTimestampsData.


        :param book: The book of this V4AudioTimestampsData.  # noqa: E501
        :type: BookId
        """

        self._book = book

    @property
    def chapter(self):
        """Gets the chapter of this V4AudioTimestampsData.  # noqa: E501


        :return: The chapter of this V4AudioTimestampsData.  # noqa: E501
        :rtype: ChapterStart
        """
        return self._chapter

    @chapter.setter
    def chapter(self, chapter):
        """Sets the chapter of this V4AudioTimestampsData.


        :param chapter: The chapter of this V4AudioTimestampsData.  # noqa: E501
        :type: ChapterStart
        """

        self._chapter = chapter

    @property
    def verse_start(self):
        """Gets the verse_start of this V4AudioTimestampsData.  # noqa: E501


        :return: The verse_start of this V4AudioTimestampsData.  # noqa: E501
        :rtype: VerseStart
        """
        return self._verse_start

    @verse_start.setter
    def verse_start(self, verse_start):
        """Sets the verse_start of this V4AudioTimestampsData.


        :param verse_start: The verse_start of this V4AudioTimestampsData.  # noqa: E501
        :type: VerseStart
        """

        self._verse_start = verse_start

    @property
    def timestamp(self):
        """Gets the timestamp of this V4AudioTimestampsData.  # noqa: E501


        :return: The timestamp of this V4AudioTimestampsData.  # noqa: E501
        :rtype: Timestamp
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this V4AudioTimestampsData.


        :param timestamp: The timestamp of this V4AudioTimestampsData.  # noqa: E501
        :type: Timestamp
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V4AudioTimestampsData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V4AudioTimestampsData):
            return True

        return self.to_dict() != other.to_dict()
