"""
Django settings for bible_research project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import yaml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CONFIG_FILE = BASE_DIR / 'config.yaml'

with open(CONFIG_FILE, 'r') as f:
    config = yaml.safe_load(f)

SECRET_KEY = config.get('SECRET_KEY')
DEBUG = config.get('DEBUG', False)
ESV_KEY = config.get('ESV_KEY')
DBT_KEY = config.get('DBT_KEY')
CONFIG_FILE = BASE_DIR / 'config.yaml'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'bible-research.vercel.app',
    'reactive-bible.vercel.app',
    'bible-research-imdtwlgzd-industr-analysers-projects.vercel.app',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # My apps
    'bible.apps.BibleConfig',
    'annotations.apps.AnnotationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bible_research.middleware.DeviceAndCountryMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://reactive-bible.vercel.app",
]

# Allow all Vercel automatically deployed PR preview origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*-vincent-uches-projects\.vercel\.app$",
]

ROOT_URLCONF = 'bible_research.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bible_research.wsgi.application'


DATABASES = config.get('DATABASES')

if not DEBUG:
    cert_path = DATABASES['default']['OPTIONS']['sslrootcert']
    DATABASES['default']['OPTIONS']['sslrootcert'] = str(BASE_DIR / cert_path)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # For 'Token' prefix
        'bible_research.authentication.BearerTokenAuthentication',  # For 'Bearer' prefix
        # TODO: Enable CSRF
        'bible_research.authentication.CSRFExemptSessionAuthentication',  # Session auth without CSRF
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Default to requiring authentication
    ],
}

def create_log_handler(handler_name, level, filename=None, max_bytes=10485760, backup_count=10):
    if DEBUG and filename:
        # Create logs directory if it doesn't exist
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
