# Generated by Django 4.2.6 on 2025-06-19 04:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the tag.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The name of the tag (e.g., 'Love', 'Grace').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tag', models.ForeignKey(blank=True, help_text='The parent tag in a hierarchical structure (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annotations.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_tag__isnull', True)), fields=('name',), name='unique_top_level_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_tag__isnull', False)), fields=('name', 'parent_tag'), name='unique_child_tag_name_per_parent'),
        ),
    ]
