# Generated by Django 4.2.6 on 2025-06-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default='NOT43A8BC94BD9D466', editable=False, help_text='Unique identifier for the note.', max_length=18, primary_key=True, serialize=False)),
                ('note_text', models.TextField(help_text='The actual content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default='TAG1E244BC016D14EA', editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The name of the tag (e.g., 'Love', 'Grace').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tag', models.ForeignKey(blank=True, help_text='The parent tag in a hierarchical structure (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annotations.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='NoteVerse',
            fields=[
                ('id', models.CharField(default='NVEDA21E7E90FC74CC', editable=False, help_text='Unique identifier for note-verse link.', max_length=18, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(help_text='The note associated with the verse.', on_delete=django.db.models.deletion.CASCADE, to='annotations.note')),
                ('verse', models.ForeignKey(help_text='The verse associated with the note.', on_delete=django.db.models.deletion.PROTECT, to='bible.verse')),
            ],
            options={
                'verbose_name': 'Note-Verse Link',
                'verbose_name_plural': 'Note-Verse Links',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='A primary tag associated with this note (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='annotations.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='verses',
            field=models.ManyToManyField(help_text='The Bible verses associated with this note.', related_name='notes', through='annotations.NoteVerse', to='bible.verse'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_tag__isnull', True)), fields=('name',), name='unique_top_level_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_tag__isnull', False)), fields=('name', 'parent_tag'), name='unique_child_tag_name_per_parent'),
        ),
    ]
