# Generated by Django 4.2.6 on 2025-06-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the tag (e.g., 'Love', 'Grace').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_tag', models.ForeignKey(blank=True, help_text='The parent tag in a hierarchical structure (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annotations.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('name', 'parent_tag')},
            },
        ),
    ]
