# Generated by Django 4.2.6 on 2025-07-23 21:18

import annotations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this note.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this tag.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default=annotations.models.generate_note_id, editable=False, help_text='Unique identifier for the note.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noteverse',
            name='id',
            field=models.CharField(default=annotations.models.generate_note_verse_id, editable=False, help_text='Unique identifier for note-verse link.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default=annotations.models.generate_tag_id, editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
