# Generated by Django 4.2.6 on 2025-06-19 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the note.', primary_key=True, serialize=False)),
                ('note_text', models.TextField(help_text='The actual content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, help_text='A primary tag associated with this note (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='annotations.tag')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteVerse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the note-verse link.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(help_text='The note associated with the verse.', on_delete=django.db.models.deletion.CASCADE, to='annotations.note')),
                ('verse', models.ForeignKey(help_text='The verse associated with the note.', on_delete=django.db.models.deletion.PROTECT, to='bible.verse')),
            ],
            options={
                'verbose_name': 'Note-Verse Link',
                'verbose_name_plural': 'Note-Verse Links',
                'ordering': ['note', 'verse'],
                'unique_together': {('note', 'verse')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='verses',
            field=models.ManyToManyField(help_text='The Bible verses associated with this note.', related_name='notes', through='annotations.NoteVerse', to='bible.verse'),
        ),
    ]
