# Generated by Django 4.2.6 on 2025-06-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_note_noteverse_note_verses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteverse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(editable=False, help_text='Unique identifier for the note.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noteverse',
            name='id',
            field=models.CharField(editable=False, help_text='Unique identifier for note-verse link.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
