# Generated by Django 4.2.6 on 2025-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_note_user_tag_user_alter_note_id_alter_noteverse_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_top_level_tag_name',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_child_tag_name_per_parent',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_tag__isnull', False)), fields=('user', 'name', 'parent_tag'), name='unique_child_tag_name_per_parent_per_user'),
        ),
    ]
