# Generated by Django 4.2.6 on 2025-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_remove_tag_unique_top_level_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False, help_text='If True, this note is publicly accessible to unauthenticated users.'),
        ),
    ]
