# Generated by Django 4.2.6 on 2025-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_noteverse_unique_together_alter_note_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='NOTCD7FC56C294548A', editable=False, help_text='Unique identifier for the note.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noteverse',
            name='id',
            field=models.CharField(default='NVE75A0CFA0ED45489', editable=False, help_text='Unique identifier for note-verse link.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default='TAG6315CACA192349D', editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
