# Generated by Django 4.2.6 on 2025-06-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_alter_note_id_alter_noteverse_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteverse',
            options={'verbose_name': 'Note-Verse Link', 'verbose_name_plural': 'Note-Verse Links'},
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='NOT7F18B48EF0C74B3', editable=False, help_text='Unique identifier for the note.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noteverse',
            name='id',
            field=models.CharField(default='NVE8B19965DBF4346F', editable=False, help_text='Unique identifier for note-verse link.', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default='TAG508ACF456CD54D1', editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
