# Generated by Django 4.2.6 on 2025-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.CharField(default='VERC0C9FE0CB923421', editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
            ],
        ),
    ]
