# Generated by Django 4.2.6 on 2025-06-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
