# Generated by Django 4.2.6 on 2025-07-23 21:18

import bible.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='id',
            field=models.CharField(default=bible.models.generate_verse_id, editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
