# Generated by Django 4.2.6 on 2025-06-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_alter_verse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='id',
            field=models.CharField(default='VERD5CC28F9D924468', editable=False, help_text='Unique identifier for the tag.', max_length=18, primary_key=True, serialize=False),
        ),
    ]
