# Generated by Django 4.2.6 on 2025-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_alter_verse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='dbt_book_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
